/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.dynamicstorage.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DynamicStorageAppEntity service. Represents a row in the &quot;DynamicStorageAppEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.dynamicstorage.model.impl.DynamicStorageAppEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.dynamicstorage.model.impl.DynamicStorageAppEntityImpl}.
 * </p>
 *
 * @author Marcellus Tavares
 * @see DynamicStorageAppEntity
 * @see com.liferay.portal.dynamicstorage.model.impl.DynamicStorageAppEntityImpl
 * @see com.liferay.portal.dynamicstorage.model.impl.DynamicStorageAppEntityModelImpl
 * @generated
 */
@ProviderType
public interface DynamicStorageAppEntityModel extends BaseModel<DynamicStorageAppEntity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dynamic storage app entity model instance should use the {@link DynamicStorageAppEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this dynamic storage app entity.
	 *
	 * @return the primary key of this dynamic storage app entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dynamic storage app entity.
	 *
	 * @param primaryKey the primary key of this dynamic storage app entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the app entity ID of this dynamic storage app entity.
	 *
	 * @return the app entity ID of this dynamic storage app entity
	 */
	public long getAppEntityId();

	/**
	 * Sets the app entity ID of this dynamic storage app entity.
	 *
	 * @param appEntityId the app entity ID of this dynamic storage app entity
	 */
	public void setAppEntityId(long appEntityId);

	/**
	 * Returns the app ID of this dynamic storage app entity.
	 *
	 * @return the app ID of this dynamic storage app entity
	 */
	public long getAppId();

	/**
	 * Sets the app ID of this dynamic storage app entity.
	 *
	 * @param appId the app ID of this dynamic storage app entity
	 */
	public void setAppId(long appId);

	/**
	 * Returns the entity name of this dynamic storage app entity.
	 *
	 * @return the entity name of this dynamic storage app entity
	 */
	@AutoEscape
	public String getEntityName();

	/**
	 * Sets the entity name of this dynamic storage app entity.
	 *
	 * @param entityName the entity name of this dynamic storage app entity
	 */
	public void setEntityName(String entityName);

	/**
	 * Returns the d d m structure ID of this dynamic storage app entity.
	 *
	 * @return the d d m structure ID of this dynamic storage app entity
	 */
	public long getDDMStructureId();

	/**
	 * Sets the d d m structure ID of this dynamic storage app entity.
	 *
	 * @param DDMStructureId the d d m structure ID of this dynamic storage app entity
	 */
	public void setDDMStructureId(long DDMStructureId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DynamicStorageAppEntity dynamicStorageAppEntity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DynamicStorageAppEntity> toCacheModel();

	@Override
	public DynamicStorageAppEntity toEscapedModel();

	@Override
	public DynamicStorageAppEntity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}